### ISSUE TITLE
[홈] 돌봄급구 및 메이트 필터 로직 구현 

### ISSUE THREAD

**Issue by Yellowtoast** [pet-sitter/pets_next_door_flutter#56]
## 🚀 기능
어떤 기능인지 설명하거나 이슈를 연결합니다.

## 📸 재현 이미지 또는 코드 샘플
해당 기능을 재현하는 이미지나 코드 샘플을 첨부할 수 있습니다.

## 📄 기능 명세
어떤 구체적인 기능들을 구현할지 명세합니다.

## 👷 작업자
작업자를 태그합니다.

## 💬 기타
기타 사항

**Comment by juan-rybczinski** [comment]
제가 지혜님이 설명해주신 문제 상황을 이제야 이해했네요.
말씀하신대로 currentTabTypeProvider를 `keepAlive: true`로 만드니 onSearchTextSubmitted에서 currentTab값을 잘 가져오는 걸 확인했어요. (ProviderObserver로 로깅해보니 지혜님이 말씀하신대로 currentTabTypeProvider를 watch하는 곳이 없으면 계속 dispose되고 있더라구요.)

아래 두가지가 궁금합니다.
1. tabController 자체는 상태가 변하는 것 같지 않은데 homeTabControllerProvider로 관리하시는 이유가 있을까요?
2. _SearchBar build 함수 내에서 currentTab 값을 전달하지 않고 HomeEvent의 onSearchTextSubmitted 함수 내에서 currentTab 값에 접근하게 구현하려고 하신 이유가 있을까요?

**Comment by Yellowtoast** [comment]
후안님께서 저번에 조언 주신 것 처럼 ProviderObserver를 사용하는게 꼭 필요하겠네요! 감사합니다 ㅎㅎ 
그리고 질문 주신 내용 답변 드려보겠습니다!

1. tabcontroller의 상태가 변할 때 마다 currentTabTypeProvider에 값을 업데이트 하려는 취지로  provider를 분리하기로 결정했었습니다! tabcontroller사용하는 방법은 두가지가 있다고 생각되는데요, 첫번째는 지금처럼 tabcontroller provider를 따로 분리하는 방식이고, 두번째는 페이지 내에서 직접 tabcontroller를 생성하여 사용하고, 페이지 내에서 addListener를 달아서 업데이트 하는 방식이 있는 것 같습니다. 다만 어짜피 tabcontroller의 상태를 공유하기 위해서는 가장 상위의 TickerProvider 상태가 필요하기 때문에, 어짜피 하위 위젯들에 TickerProvider 상태를 넘겨주어 직접 homeTabControllerProvider를 찾도록 하거나, 지금과 같이 tabController를 직접 argument로 전달해야 할 것 같습니다. 결과적으로 tabcontroller를 따로 provider로 분리하는 것에 큰 의미가 있나..라고 생각하면 답은 '아니다' 인 것 같습니다! 오히려 provider를 두지 않고 페이지 내부에서 직접 tabcontroller를 생성하고 사용하는 편이 사용 목적에 더 맞지 않나 하는 생각이 듭니다. 후안님께서 제안해주신 질문을 기반으로 생각해보니 homeTabControllerProvider를 현재 상황에서는 굳이 두지 않아도 될 것 같습니다!

2. 이경우는, 제가 계속 값이 바뀌지 않아서 왜 안바뀔까.. 고민하다가 테스트 용도로 임시로 넣어놓은 코드입니다..ㅎㅎㅎ 이제 원인을 찾았으니, argument로 전달하지 않고 onSearchTextSubmitted내부에서 바로 currentTab과 filter 값을 ref로 바로 접근하여 사용하도록 바꿀 것 같습니다!
